# Deliverable 3. Create a Travel Itinerary Map.

In [34]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import gmaps.datasets
import numpy as np

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [35]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

City_ID            City Country  Max Temp Current Weather    Lat     Lng  \
0        0        Lockport      US     88.00           Clear  41.59  -88.06   
1        5  Candido Mendes      BR     76.19          Clouds  -1.45  -45.72   
2        6    Porto Walter      BR     78.06          Clouds  -8.27  -72.74   
3        8        Portland      US     82.99           Clear  45.52 -122.68   
4        9          Ixtapa      MX     86.00          Clouds  20.70 -105.20   

                      Hotel Name  
0             Big Run Wolf Ranch  
1            Quebrada Do Mlk PJL  
2                    Hotel Silva  
3  Portland Marriott City Center  
4  Container Inn Puerto Vallarta

In [37]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Weather}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [38]:
# 4a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig



Figure(layout=FigureLayout(height='420px'))

In [47]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.
vacation_start = vacation_df.loc[vacation_df["City"] == "Lazaro Cardenas", :]
vacation_end = vacation_df.loc[vacation_df["City"] == "Lazaro Cardenas", :]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == "Ixtapa", :]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == "Tomatlan", :]
vacation_stop3 = vacation_df.loc[vacation_df["City"] == "San Patricio", :]
vacation_stop3


City_ID          City Country  Max Temp Current Weather    Lat    Lng  \
135      403  San Patricio      MX      82.4          Clouds  19.22 -104.7   

            Hotel Name  
135  Hotel Cabo Blanco

In [48]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy(), vacation_start["Lng"].to_numpy()
end = vacation_end["Lat"].to_numpy(), vacation_end["Lng"].to_numpy()
stop1 = vacation_stop1["Lat"].to_numpy(), vacation_stop1["Lng"].to_numpy()
stop2 = vacation_stop2["Lat"].to_numpy(), vacation_stop2["Lng"].to_numpy()
stop3 = vacation_stop3["Lat"].to_numpy(), vacation_stop3["Lng"].to_numpy()
print(start)
print(stop1)
print(stop2)
print(stop3)

(array([17.96]), array([-102.2]))
(array([20.7]), array([-105.2]))
(array([19.93]), array([-105.25]))
(array([19.22]), array([-104.7]))


In [55]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

Lazaro_Cardenas = (17.96, -102.2)
Ixtapa = (20.7, -105.2)
Tomatlan = (19.93, -105.25)
San_Patricio = (19.22, -104.7)
fig = gmaps.figure()
mexico_vacation = gmaps.directions_layer(
        Lazaro_Cardenas, Lazaro_Cardenas, waypoints=[Ixtapa,Tomatlan,San_Patricio,],
        travel_mode='DRIVING')
fig.add_layer(mexico_vacation)
fig

Figure(layout=FigureLayout(height='420px'))

In [56]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID             City Country  Max Temp Current Weather    Lat     Lng  \
0      697  Lazaro Cardenas      MX     76.50            Rain  17.96 -102.20   
1        9           Ixtapa      MX     86.00          Clouds  20.70 -105.20   
2      690         Tomatlan      MX     82.42            Rain  19.93 -105.25   
3      403     San Patricio      MX     82.40          Clouds  19.22 -104.70   

                          Hotel Name  
0  Collection O Hotel Quinta Antigua  
1      Container Inn Puerto Vallarta  
2                       Norma franco  
3                  Hotel Cabo Blanco

In [57]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Weather}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [60]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))